"""initial models

Revision ID: 0a5cea2ee1e6
Revises: 
Create Date: 2026-09-25 12:13:24.707448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a5cea2ee1e6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_providers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.Enum('INTERNAL', 'EXTERNAL', name='providerkind', native_enum=False, length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('products',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sku', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_table('reservations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(length=160), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('RESERVING', 'ACTIVE', 'CONFIRMING', 'RELEASING', 'CONFIRMED', 'CANCELLED', 'EXPIRED', name='reservationstatus', native_enum=False, length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('release_reason', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'idempotency_key', name='uq_reservation_user_idempotency')
    )
    op.create_index('ix_reservation_status_expiry', 'reservations', ['status', 'expires_at'], unique=False)
    op.create_table('stock_sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('provider_sku', sa.String(length=160), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['provider_id'], ['inventory_providers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'provider_id', name='uq_stock_source_product_provider')
    )
    op.create_table('internal_stock',
    sa.Column('stock_source_id', sa.Uuid(), nullable=False),
    sa.Column('on_hand', sa.Integer(), nullable=False),
    sa.Column('held', sa.Integer(), nullable=False),
    sa.CheckConstraint('held <= on_hand', name='ck_internal_stock_held_lte_on_hand'),
    sa.CheckConstraint('held >= 0', name='ck_internal_stock_held_nonnegative'),
    sa.CheckConstraint('on_hand >= 0', name='ck_internal_stock_on_hand_nonnegative'),
    sa.ForeignKeyConstraint(['stock_source_id'], ['stock_sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('stock_source_id')
    )
    op.create_table('reservation_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reservation_id', sa.Uuid(), nullable=False),
    sa.Column('stock_source_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('HOLD_PENDING', 'HOLD_UNKNOWN', 'HELD', 'CONFIRM_PENDING', 'CONFIRM_UNKNOWN', 'CONFIRMED', 'RELEASE_PENDING', 'RELEASE_UNKNOWN', 'RELEASED', 'FAILED', name='reservationlinestatus', native_enum=False, length=32), nullable=False),
    sa.Column('external_hold_ref', sa.String(length=255), nullable=True),
    sa.Column('held_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('quantity > 0', name='ck_reservation_line_quantity_positive'),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stock_source_id'], ['stock_sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reservation_id', 'stock_source_id', name='uq_reservation_line_source')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservation_lines')
    op.drop_table('internal_stock')
    op.drop_table('stock_sources')
    op.drop_index('ix_reservation_status_expiry', table_name='reservations')
    op.drop_table('reservations')
    op.drop_table('products')
    op.drop_table('inventory_providers')
    # ### end Alembic commands ###
